git-merge: extract git_merge_limited()

diff --git a/git-merge b/git-merge
--- a/git-merge
+++ b/git-merge
@@ -23,6 +23,79 @@ reprepro checkupdate sid
 # ^-- loop <--------------------
 #
 
+git_merge_limited()
+{
+    # now merge, all but those $reprepro_managed_dirs
+    git merge --no-commit $REMOTE_BRANCH
+
+
+    # don't re-`add' files which WE added, but 'reprepro removed', but remote added?
+    if [[ -z $(git status --short pool|sed -n -e 's/^A  //p') ]]
+    then
+        echo "remote has older version:"
+        git status --short pool|sed -n -e 's/^A  //p'
+        read _
+        git status --short pool|sed -n -e 's/^A  //p'| xargs --no-run-if-empty rm -v
+    fi
+
+    # deleted or `modified' files:
+    # now new (but old) files might appear in pool!!!
+
+    # fixme: this is not good. Changing files is alarming!
+    # but then the files will oscilate, if we never 'merge' on any node.
+    if git status --short pool|sed -n -e 's/^M  //p' | xargs --no-run-if-empty rm -v
+       git diff  --stat  -- pool/
+    then
+        echo "reprepro resolved the difference using its algorithm. We cannot handle updates"
+        read _
+        # reset:
+        # xargs --max-args 1 --no-run-if-empty git checkout HEAD
+    else
+        git add pool/
+        # interesting: what files?
+        git diff --staged --stat  -- pool/
+    fi
+
+
+
+    # `conflicts' in dists/ are irresolvable:
+
+    # fixme: this must not change anything!
+    if [[ -n $(git ls-files --unmerged  dists/ ) ]]
+    then
+        cecho red "conflicts detected in these files:"
+        git ls-files --unmerged dists/
+        echo "resetting them"
+
+        git ls-files --unmerged dists/ | cut --fields 2 | sort --unique |\
+            xargs --max-args 1 --no-run-if-empty git checkout HEAD
+    fi
+
+    # and any difference if they have different size?
+
+    # if ! git diff --staged --stat  HEAD;
+    if ! git diff --name-only --cached --exit-code dists/
+    then
+        echo "Some dists changed: so have to re-sign:"; read ignored
+        # but maybe some conflicted files were ignored !
+        reprepro export
+        # stage them!
+        git add dists/
+    else
+        :
+        # git merge --abort
+    fi
+
+
+    if ! git diff --staged --exit-code HEAD;
+    then
+        git commit -m 'merge'
+    fi
+}
+
+
+
+
 
 # return true if pushed successfully
 update_once()
@@ -48,49 +121,7 @@ update_once()
 
 
         info "try to merge with remote -- ignoring dists/"
-        # now merge, all but those $reprepro_managed_dirs
-        git merge --no-commit $REMOTE_BRANCH
-
-        # don't re-add files which WE added, but 'reprepro removed', but remote added?
-        git status --short pool|sed -n -e 's/^A  //p'| xargs --no-run-if-empty rm -v
-
-        # now new (but old) files might appear in pool!!!
-        git add pool/
-        # interesting: what files?
-        git diff --staged --stat  -- pool/
-
-        # dists ..conflicts
-        # git reset   --hard  dists/
-
-        # fixme: this must not change anything!
-        if [[ -n $(git ls-files --unmerged  dists/ ) ]]
-        then
-            cecho red "conflicts detected in these files:"
-            git ls-files --unmerged dists/
-            echo "resetting them"
-
-            git ls-files --unmerged dists/ | cut --fields 2 | sort --unique |\
-                xargs --max-args 1 --no-run-if-empty git checkout HEAD
-        fi
-
-        # so
-        # if ! git diff --staged --stat  HEAD;
-        if ! git diff --name-only --cached --exit-code dists/
-        then
-            echo "Some dists changed: so have to re-sign:"; read ignored
-            # but maybe some conflicted files were ignored !
-            reprepro export
-            # stage them!
-            git add dists/
-        else
-            :
-            # git merge --abort
-        fi
-
-        if ! git diff --staged --exit-code HEAD;
-        then
-            git commit -m 'merge'
-        fi
+        git_merge_limited
     fi
 
     # don't add ?
