sanitize reprepro -- db version different

diff --git a/.github/workflows/import.yml b/.github/workflows/import.yml
--- a/.github/workflows/import.yml
+++ b/.github/workflows/import.yml
@@ -57,6 +57,16 @@ jobs:
           # mmc: changes, .dsc
           ls -l incoming
 
+      - name: Sanitize Reprepro
+        run: |
+          ldd $(which reprepro) |grep libdb
+          # If the DB exists but reprepro fails to even check its version,
+          # it's likely a BDB version mismatch.
+          if ! reprepro -b ./apt-data dumpversion; then
+          echo "Database version mismatch detected. Clearing old DB..."
+          rm -rf ./apt-data/db
+          fi
+
       - name: Run Reprepro
         run: |
           # Use config from main, but write data to apt-data folder
